spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SamuelRuwe/pure-geniusness-config

server:
  port: 8081

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/